title: <p align="center"> Pratik Pattanaik </p>
logo: /assets/img/cat.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pratik-pattanaik-862972127/">LinkedIn</a> |
  <a href="https://github.com/pattanaikay">GitHub</a>
  
  <br>   
  I'm working on Cloud Development, and plan to shift to Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with Accenture India in the Industry X vertical. 
  Working in cloud domain for 1.5 years.
  <br>
  </p>
  
theme: jekyll-theme-minimal
